[package]
name = "task_mate"
version = "0.1.0"
edition = "2021"
rocket = "0.5.0"
rocket_contrib = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


